# Generated by Django 5.1.2 on 2025-09-04 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_gender_profile_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('prefer_not', 'Prefer Not to Say')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pronouns',
            field=models.CharField(blank=True, choices=[('he_him', 'He/Him'), ('she_her', 'She/Her'), ('they_them', 'They/Them')], max_length=20, null=True),
        ),
    ]
